name: MAD Practical Test
on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v2
        
      - name: Checkout Test Scripts
        uses: actions/checkout@v2
        with:
          repository: lowkh/MAD_JunitPrac2
          path: testDirectory
      - name: Check files
        run: |
            ls
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.7'
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check JDK
        run: |
          ls /usr/lib/jvm/
  
      - name: Run Android Tests
        run: ./gradlew test -Dorg.gradle.java.home=/usr/lib/jvm/temurin-17-jdk-amd64
        
      - name: Build Project
        run: ./gradlew assemble -Dorg.gradle.java.home=/usr/lib/jvm/temurin-17-jdk-amd64
